Update theme.view.php issue Make Theme UI clearer #19
chishiki/perihelion pull request #20
Opened 2021-07-14 03:04 UTC by siramsay

2021-07-14 05:55 UTC, chishiki commented on deploy/src/perihelion/php/view/theme.view.php
> +															$h .= "<a class=\"btn btn-secondary btn-sm\" href=\"" . $select_theme . "\"><span class=\"\" style=\"color:#fff;\"></span> Select</a>";
this change is fine thanks for plugging away at it

just one thing when we add text we want to remember to use `Lang::getLang('xxxxxxx')`

2021-07-14 06:12 UTC, siramsay commented on deploy/src/perihelion/php/view/theme.view.php
> +															$h .= "<a class=\"btn btn-secondary btn-sm\" href=\"" . $select_theme . "\"><span class=\"\" style=\"color:#fff;\"></span> Select</a>";
nice, I'll add the Lang::getLang('xxxxxxx')

2021-07-14 06:40 UTC, chishiki commented on deploy/src/perihelion/php/view/theme.view.php
> +															$h .= "<a class=\"btn btn-secondary btn-sm\" href=\"" . $select_theme . "\"><span class=\"\" style=\"color:#fff;\"></span> Select</a>";
thanks!

2021-07-15 09:55 UTC, chishiki requested changes
lemme know when you've localized those "select" and i'll push this in thanks!

2021-07-16 01:56 UTC, siramsay commented on deploy/src/perihelion/php/view/theme.view.php
> +															$h .= "<a class=\"btn btn-secondary btn-sm\" href=\"" . $select_theme . "\"><span class=\"\" style=\"color:#fff;\"></span> Select</a>";
just added that and this says outdated now. unsure if you can see the new changes?

2021-07-16 01:58 UTC, siramsay commented
It says added 2 commits above so I guess they are added to the pull request, please let me if this is done right. Thanks

2021-08-11 05:52 UTC, merged